services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${JELLYFIN_UID}:${JELLYFIN_GID}
    network_mode: 'host'
    volumes:
      - /home/rakitha/apps/JellyFin/config:/config
      - /home/rakitha/apps/JellyFin/cache:/cache
      - type: bind
        source: /home/rakitha/sambashare
        target: /media
      
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - ${JELLYFIN_PUBLISHED_URL}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    environment:
      - PUID=${QBITTORENT_PUID}
      - PGID=${QBITTORENT_PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORENT_WEBUI_PORT}
      - TORRENTING_PORT=${QBITTORENT_TORRENTING_PORT}

    volumes:
      - /home/rakitha/apps/qbittorrent/config:/config
      - /home/rakitha/apps/qbittorrent/downloads:/downloads
    ports:
      - "${QBITTORENT_WEBUI_PORT}:9090"
      - "${QBITTORENT_TORRENTING_PORT}:6881"
      - "${QBITTORENT_TORRENTING_PORT}:6881/udp"
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${SONARR_PGID}
      - TZ=${TZ}
    volumes:
      - /home/rakitha/apps/sonarr/data:/config
      - /home/rakitha/sambashare/Tv_Shows:/tv
      - /home/rakitha/apps/qbittorrent/downloads:/downloads
    ports:
      - "${SONARR_PORT}:8989"
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
  radar:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: 
      - PUID=${RADARR_PUID}
      - PGID=${RADARR_PGID}
      - TZ=${TZ}
    volumes:
      - /home/rakitha/apps/radarr/data:/config
      - /home/rakitha/sambashare/Movies:/movies
      - /home/rakitha/apps/qbittorrent/downloads:/downloads
    ports:
      - "${RADARR_PORT}:7878"
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${SONARR_PGID}
      - TZ=${TZ}
    volumes:
      - /home/rakitha/apps/prowlarr/data:/config
    ports:
      - "${PROWLARR_PORT}:9696"
    restart: unless-stopped
  uptimekuma:
    image: louislam/uptime-kuma:latest
    volumes: 
      - /home/rakitha/apps/uptimekuma:/app/data
    container_name: uptime-kuma
    ports:
      - "${UPTIMEKUMA_PORT}:3001"
    restart: always
